name = "Plasmapower"
version = "1.0.0"
defaultTargets = ["Plasmapower"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"

[[lean_lib]]
name = "Plasmapower"

[[lean_exe]]
name = "plasmapower"
root = "Main"